### ISSUE TITLE
Some parameters are not supported.

### ISSUE THREAD

**Issue by cihangirbesiktas** [nicgrayson/terraform-provider-marathon#62]
The following parameters are not supported in the plugin for app definition.

- disk
- gpus
- max_launch_delay_seconds
- unreachable_strategy
- kill_selection

could you add them?

**Comment by luisdavim** [comment]
some of these seem to be covered by PR #56 .

**Comment by luisdavim** [comment]
Now that #56 was merged, merging #64 would close this issue.

**Comment by nicgrayson** [comment]
#64 and #56 are merged. closing.
